# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react_native_appcenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react_native_appcenter
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'react_native_appcenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'react_native_appcenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react_native_appcenter-tvOS

  target 'react_native_appcenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
